### ISSUE TITLE
FIX: storage engine slot is incorrect

### ISSUE THREAD

**Issue by lujiashun** [andyli029/mysql-server-mysql-8.0.30#115]
# 1.   How to reproduce it 
```
 CREATE TABLE `tmp_loaddata` (
`id` int(11) NOT NULL,
`name` varchar(10) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=tianmu;
```
```
echo "1,new update"   >  /data/1.txt
echo "2,new update"   >> /data/1.txt
echo "3,new update"   >> /data/1.txt
```
```
LOAD DATA INFILE '/data/1.txt' Into TABLE tmp_loaddata FIELDS TERMINATED BY ',';
```
2. then carshed

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fec489cf859 in __GI_abort () at abort.c:79
#2  0x00007fec489cf729 in __assert_fail_base (fmt=0x7fec48b65588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55961716283c "n < size()",
    file=0x5596171627f8 "/data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h", line=231, function=<optimized out>) at assert.c:92
#3  0x00007fec489e0fd6 in __GI___assert_fail (assertion=0x55961716283c "n < size()", file=0x5596171627f8 "/data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h",
    line=231,
    function=0x559617162758 "Element_type& Prealloced_array<Element_type, Prealloc>::at(size_t) [with Element_type = Ha_data; long unsigned int Prealloc = 15; size_t = long unsigned int]") at assert.c:101
#4  0x0000559613f84f0f in Prealloced_array<Ha_data, 15ul>::at (this=0x7fe6f40025c8, n=18446744073709551615) at /data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h:231
#5  0x0000559613f84eb5 in Prealloced_array<Ha_data, 15ul>::operator[] (this=0x7fe6f40025c8, n=18446744073709551615)
    at /data/codebase/mysql-server-mysql-8.0.30/include/prealloced_array.h:240
#6  0x0000559613f84cea in THD::get_ha_data (this=0x7fe6f4000c50, slot=-1) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_class.h:1599
#7  0x00005596161141b8 in Tianmu::core::Engine::GetTx (this=0x55961dbd4380, thd=0x7fe6f4000c50) at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/core/engine.cpp:914
#8  0x000055961624c342 in Tianmu::dbhandler::TianmuHandler::external_lock (this=0x7fe6f415add0, thd=0x7fe6f4000c50, lock_type=1)
    at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/handler/tianmu_handler.cpp:269
#9  0x000055961426bbdb in handler::ha_external_lock (this=0x7fe6f415add0, thd=0x7fe6f4000c50, lock_type=1) at /data/codebase/mysql-server-mysql-8.0.30/sql/handler.cc:7790
#10 0x00005596144b9cc4 in lock_external (thd=0x7fe6f4000c50, tables=0x7fe6f4028bf8, count=1) at /data/codebase/mysql-server-mysql-8.0.30/sql/lock.cc:393
#11 0x00005596144b9949 in mysql_lock_tables (thd=0x7fe6f4000c50, tables=0x7fe6f415e620, count=1, flags=0) at /data/codebase/mysql-server-mysql-8.0.30/sql/lock.cc:337
#12 0x0000559613d4caaa in lock_tables (thd=0x7fe6f4000c50, tables=0x7fe6f415dfb0, count=1, flags=0) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_base.cc:6900
#13 0x0000559613d4c0d6 in open_and_lock_tables (thd=0x7fe6f4000c50, tables=0x7fe6f415dfb0, flags=0, prelocking_strategy=0x7fec003eeeb0)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_base.cc:6594
#14 0x0000559613ca6752 in open_and_lock_tables (thd=0x7fe6f4000c50, tables=0x7fe6f415dfb0, flags=0) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_base.h:470
#15 0x00005596145e370a in Sql_cmd_load_table::execute_inner (this=0x7fe6f415de70, thd=0x7fe6f4000c50, handle_duplicates=DUP_ERROR)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_load.cc:249
#16 0x00005596145eaf12 in Sql_cmd_load_table::execute (this=0x7fe6f415de70, thd=0x7fe6f4000c50) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_load.cc:2150
#17 0x0000559613e58c56 in mysql_execute_command (thd=0x7fe6f4000c50, first_level=true) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:3577
#18 0x0000559613e5e532 in dispatch_sql_command (thd=0x7fe6f4000c50, parser_state=0x7fec003f0b90) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:5239
#19 0x0000559613e53fb1 in dispatch_command (thd=0x7fe6f4000c50, com_data=0x7fec003f14e0, command=COM_QUERY) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:1959
#20 0x0000559613e52028 in do_command (thd=0x7fe6f4000c50) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_parse.cc:1362
#21 0x000055961408e8cf in handle_connection (arg=0x55961db697c0) at /data/codebase/mysql-server-mysql-8.0.30/sql/conn_handler/connection_handler_per_thread.cc:302
#22 0x0000559615fb05d4 in pfs_spawn_thread (arg=0x559620316bf0) at /data/codebase/mysql-server-mysql-8.0.30/storage/perfschema/pfs.cc:2942
#23 0x00007fec49bc1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#24 0x00007fec48acc133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

3. the slot variables is  set incorrectly(-1, actual value should be 8)
3.1 rcbase_init_func is invoked firstly, sloth value is -1;
#0  Tianmu::dbhandler::rcbase_init_func (p=0x5555615ae040) at /data/codebase/mysql-server-mysql-8.0.30/storage/tianmu/handler/tianmu_handler_com.cpp:187
```
#1  0x0000555559658a1d in ha_initialize_handlerton (plugin=0x55556158c350) at /data/codebase/mysql-server-mysql-8.0.30/sql/handler.cc:774
#2  0x000055555928c4b5 in plugin_initialize (plugin=0x55556158c350) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_plugin.cc:1299
#3  0x000055555928cc66 in plugin_init_initialize_and_reap () at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_plugin.cc:1457
#4  0x000055555928de60 in plugin_register_dynamic_and_init_all (argc=0x55555ec2f990 <remaining_argc>, argv=0x55555f408300, flags=0)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_plugin.cc:1821
#5  0x0000555559083ffb in init_server_components () at /data/codebase/mysql-server-mysql-8.0.30/sql/mysqld.cc:6435
#6  0x0000555559087f42 in mysqld_main (argc=18, argv=0x55555f408300) at /data/codebase/mysql-server-mysql-8.0.30/sql/mysqld.cc:7686
#7  0x0000555559074fcd in main (argc=9, argv=0x7fffffffeb98) at /data/codebase/mysql-server-mysql-8.0.30/sql/main.cc:25
```
3.2 
(gdb) ha_initialize_handlerton::822 lines,the values is firly set to 8.
```
#0  ha_initialize_handlerton (plugin=0x55556158c350) at /data/codebase/mysql-server-mysql-8.0.30/sql/handler.cc:822
#1  0x000055555928c4b5 in plugin_initialize (plugin=0x55556158c350) at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_plugin.cc:1299
#2  0x000055555928cc66 in plugin_init_initialize_and_reap () at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_plugin.cc:1457
#3  0x000055555928de60 in plugin_register_dynamic_and_init_all (argc=0x55555ec2f990 <remaining_argc>, argv=0x55555f408300, flags=0)
    at /data/codebase/mysql-server-mysql-8.0.30/sql/sql_plugin.cc:1821
#4  0x0000555559083ffb in init_server_components () at /data/codebase/mysql-server-mysql-8.0.30/sql/mysqld.cc:6435
#5  0x0000555559087f42 in mysqld_main (argc=18, argv=0x55555f408300) at /data/codebase/mysql-server-mysql-8.0.30/sql/mysqld.cc:7686
#6  0x0000555559074fcd in main (argc=9, argv=0x7fffffffeb98) at /data/codebase/mysql-server-mysql-8.0.30/sql/main.cc:25
```

**Comment by andyli029** [comment]
```
Tianmu::dbhandler::TianmuHandler::external_lock tianmu_handler.cpp:269
handler::ha_external_lock handler.cc:7790
lock_external lock.cc:393
mysql_lock_tables lock.cc:337
lock_tables sql_base.cc:6900
Sql_cmd_dml::execute sql_select.cc:582
mysql_execute_command sql_parse.cc:4604
dispatch_sql_command sql_parse.cc:5239
dispatch_command sql_parse.cc:1959
do_command sql_parse.cc:1362
handle_connection connection_handler_per_thread.cc:302
pfs_spawn_thread pfs.cc:2942
start_thread 0x00007ffff7f97609
clone 0x00007ffff6e6f133
```
